gdk/gdk.go
gtk/gtk.go

gtk: add missing GtkFileChooserDialog case in cast()

gdk: add GdkEventScroll, fix memory leak in Pixbuf & simplify code

---

gdk/gdk_deprecated_since_3_16.go
gtk/gtk_deprecated_since_3_16.go

Sorry, the method was moved to the wrong package. My bad.

Fix pull request #4

---

cairo/cairo.go

Partial implementation of Cairo's text rendering API:
http://cairographics.org/manual/cairo-text.html

Add support for rendering text

---

gtk/gtk.go

- gtk_widget_get_can_default 
- gtk_widget_set_can_default 
- gtk_window_get_default_widget 
- gtk_window_set_default

Adds some wrappers 

---

glib/glib.go

This happend when the return value used in a Emit() call was finalized and the
signal didn't return any value. The GValue will still be uninitialized and cant
be unsetted.
Unsetting such GValues return a message:
`g_value_unset: assertion 'G_IS_VALUE (value)' failed`

Fix incorrect finalization of alloc-ed but uninit-ed GValues

---

gdk/gdk.go
gdk/gdk_inmem.go
gdk/gdk_inmem.h
gtk/gtk.go
gtk/tree_view.go

Hi,
working with treeview/treestore required me to add some new wrappers which were missing until now. Just want to share...
Cheers
Axel

Some new wrappers

---

gdk/gdk.go
gtk/widget.go

Sharing two more wrappers that I needed...

Adding wrappers for gdk_pixbuf_copy() and gtk_widget_queue_draw_area()

---

gtk/gtk_since_3_12.go
gtk/gtk_since_3_12.go.h

First Pull Request I ever made so I don't know if you have all you need.
This should be all functions needed for the ActionBar, I followed naming scheme etc I think.

Added GtkActionBar support

---

gdk/gdk.go
gdk/gdk.go.h
gtk/gtk.go

DeviceManager methods, Device grabbing and a couple of little fixes

---

gtk/gtk.go.h
gtk/level_bar.go
gtk/level_bar_since_3_8.go

I created separate files for it because of #15. If preferred I can change that of course.

This adds bindings for GtkLevelBar

---

glib/list.go
glib/list_test.go
gtk/gtk.go

* Add `Nth()`, `Foreach()` and `FreeFull()`.
* Make `DataWrapped()` and `NthDataWrapped()` the only interface to list data.

glib.List enhancements

---

gtk/app_chooser.go
gtk/color_chooser.go
gtk/gtk.go
gtk/gtk.go.h

Added AppChooser, ...Button, ...Widget and ...Dialog, ColorChooser and ...Dialog.

AppChoosers and ColorChoosers

---

gtk/gtk.go

Fix gtk.Init building on go 1.6

---

gtk/gtk.go

Made the interface more Go like, fix issue with the old implementation.

Fix TreeSelection.GetSelected interface (#94)

---

gtk/gtk.go
gtk/gtk.go.h

Bindings for GtkSizeGroup

---

gtk/application.go
gtk/gtk.go

Needed so that 'activate' signal callback will work

Add marshalling for GtkApplication

---

gtk/gtk.go

Add support for gtk_tree_model_iter_nth_child

---

glib/settings_schema_source.go

This change adds a wrapper for `g_settings_schema_source_list_schemas()`

implement ListSchemas for SettingsSchemaSource

---

gtk/gtk.go
gtk/gtk.go.h
gtk/gtk_since_3_18.go

This change adds GtkOverlay support.
This is my first change to gotk3, and I did it mostly by following the patterns of other classes, so I would be completely unsurprised if there are mistakes. Please review carefully. Thanks.

Added support for GtkOverlay.

---

gtk/window.go

Hello, just added two methods to window object.

Add ActivateKey and AddMnemonic to Window

---

glib/gbinding.go
glib/glib.go.h

Implemented basic support for property binding via GBinding

Support for property binding (GBinding)

---

gtk/gtk_since_3_16.go

Useful for aligning text labels

add gtk 3.16 gtk_label_{get,set}_{x,y}align

---

gdk/gdk.go

add wrappers for
- gdk_cursor_new_from_name
- gdk_window_set_cursor

Add wrappers for some gdk cursor functions

---

gtk/gtk.go.h
gtk/gtk_export.go
gtk/print.go
gtk/print_test.go

Add the missing functions to GtkPrintOperation and GtkPrintSettings to complete printing support.

Add missing functions for printing.

---

gdk/gdk.go
gdk/gdk_deprecated_since_3_20.go
gdk/gdk_deprecated_since_3_22.go
gdk/screen.go
gtk/gtk.go
gtk/gtk_deprecated_since_3_20.go
gtk/gtk_deprecated_since_3_22.go
gtk/text_iter.go
gtk/window.go

Move some deprecated methods to the corresponding files.

---

gtk/gtk_since_3_12.go
gtk/gtk_since_3_12.go.h

This is a widget added in gtk 3.12. Wanted to use it in a project, but didn't see wrappers for it, so I've added some. Hopefully this can be merged in. Let me know if there are any issues. Thanks.

Add wrappers for GtkFlowBox and GtkFlowBoxChild

---

gdk/gdk.go

Fix pixbuf memory leaks. Fixes #163.

---

gtk/gtk.go
gtk/gtk.go.h

Implements SetMenuModel and GetMenuModel on gtk.MenuButton.
Please check if the pointer magic in SetMenuModel is the correct approach for this issue.

Implement gtk_menu_button_{set,get}_menu_model

---

gtk/gdk.go
gtk/gtk.go
gtk/gtk.go.h
gtk/icon_view.go
gtk/tooltip.go

- adds tooltip widget
- adds support for tooltip methods in iconview widget
- naming cleanup in iconview widget

add tooltip widget, add tooltip methods for iconview

---

gtk/box_since_3_12.go

I'm very new to Go. This appears to work as expected!
Reference: https://developer.gnome.org/gtk3/stable/GtkBox.html#gtk-box-get-center-widget

Implement gtk_box_get_center_widget + gtk_box_set_center_widget

---

gtk/gtk.go

Add InitCheck(), wrapping gtk_init_check()

---

glib/glib.go

Fix IdleAdd and TimeoutAdd

---

gtk/gtk.go
gtk/tree_view_column.go

multiple patches

---

gtk/gtk_since_3_20.go.h

Fix missing C.toGtkFileChooser

---

gtk/gtk_since_3_20.go

This addresses the build errors reported in https://github.com/gotk3/gotk3/issues/283.
I have no idea what's the reason for these errors though, so these changes may break the build for others (e.g. against different gtk versions - just a guess).

Fix various type casts from/to C.gchar/C.char

---

.travis.yml

See https://docs.travis-ci.com/user/languages/go/#go-import-path.

Replace Travis hack for building on forks

---

gtk/combo_box.go
gtk/gtk_export_since_3_10.go
gtk/gtk_since_3_10.go
gtk/gtk_since_3_10.go.h
gtk/gtk_since_3_16.go
gtk/shortcutswindow_since_3_22.go
gtk/shortcutswindow_since_3_22.go.h

Adding changes from PR #203 as the PR was forgotten since it has been failing.

Xsmurf multiple

---

README.md
gtk/fixed.go
gtk/fixed.go.h

I have added bindings for the `GtkFixed` type and it's two methods `put` and `move`.
I have also created a pull request in https://github.com/gotk3/gotk3-examples that contains a usage example. You can find the pr here: https://github.com/gotk3/gotk3-examples/pull/11

Add new bindings for GtkFixed

---

gtk/widget.go
gtk/window.go

Added gtk.Widget#GetScreen() and removed gtk.Window#GetScreen() 

---

gdk/gdk_since_3_16.go
gdk/gdk_since_3_16.go.h
gdk/gdk_since_3_8.go
gdk/gdk_since_3_8.go.h
gtk/glarea.go
gtk/gtk_since_3_16.go.h
gtk/gtk_since_3_8.go
gtk/widget_export_since_3_8.go
gtk/widget_since_3_8.go
gtk/widget_since_3_8.go.h

Added GdkGLContext and GtkGLArea so that a GLArea widget can be included into the UI, and one can use OpenGL to draw to the widget.

Added GdkGLContext, GtkGLArea, GdkFrameClock, GdkFrameTimings, GdkFrameColckPhase, and GtkTickCallback

---

gtk/gtk.go
gtk/gtk.go.h

Add support for GTK toggle tool buttons.

Wrap GtkToggleToolButton

---

gtk/gtk.go

please merge this wrapper around gtk_statusbar_remove_all()

Add a wrapper around gtk_statusbar_remove_all()

---

gtk/gtk.go

Please merge this wrapper around gtk_menu_item_set_use_underline()

Add a wrapper around gtk_menu_item_set_use_underline() and gtk_menu_item_get_use_underline()

---

gtk/tree_view.go

Add TreeView:
gtk_tree_view_scroll_to_cell()

Add TreeView

---

gtk/gtk.go

Add TreeSelection functions #1
gtk_tree_selection_unselect_iter()
gtk_tree_selection_iter_is_selected()
gtk_tree_selection_select_range()

 Adds TreeSelection functions #1

---

glib/glib.go
glib/gmain_context.go

Add glib function GlibSource:
g_source_destroy()
g_source_is_destroyed ()
g_source_unref()
g_source_ref()
g_source_remove()
Add glib function GlibMainContext:
g_main_context_find_source_by_id()
g_main_context_pending()

Add glib functions

---

gtk/tree_view.go

returned path and column were always nil

fix treeview.GetPathAtPos()

---

gtk/gtk.go

Adds TextBuffer:
gtk_text_buffer_delete_mark()
gtk_text_buffer_delete_mark_by_name()

Adds TextBuffer

---

gtk/gtk_since_3_12.go

Add TreePath in since 3.12: 
gtk_tree_path_new_from_indicesv()

Add TreePath: gtk_tree_path_new_from_indicesv()

---

gtk/gtk.go

Adds TreePath #1:
gtk_tree_path_new_first()
gtk_tree_path_append_index()
gtk_tree_path_prepend_index()

Adds TreePath #1

---

gtk/gtk.go

Adds TreePath #4:
gtk_tree_path_down()
gtk_tree_path_is_ancestor()
gtk_tree_path_is_descendant()

Adds TreePath #4

---

gtk/gtk.go
gtk/gtk.go.h
gtk/gtk_export.go

Adds TreeModel ForEach function:
gtk_tree_model_foreach()
With prototype:
TreeModelForeachFunc
His type:
treeModelForeachFuncData
His struct:
treeModelForeachFuncRegistry

Adds TreeModel: gtk_tree_model_foreach()

---

gtk/gtk.go

Adds TreeStore:
gtk_tree_store_insert_before()
gtk_tree_store_insert_after()

Adds TreeStore

---

gtk/gtk.go

Adds TreePath #3:
gtk_tree_path_next()
gtk_tree_path_prev()
gtk_tree_path_up()

Adds TreePath #3

---

gtk/gtk.go
gtk/gtk.go.h

Add Dialog:
Add gtk_dialog_new_with_buttons() 
Hi, following, a piece of code to illustrate function ...
```
package main
import (
"fmt"
"log"
"github.com/gotk3/gotk3/glib"
"github.com/gotk3/gotk3/gtk"
)
func main() {
var dialog *gtk.Dialog
var err error
var lbl *gtk.Label
var mainWin *gtk.Window
gtk.Init(nil)
if lbl, err = gtk.LabelNew(""); err == nil {
lbl.SetMarkup(`<b><span foreground="#A40000FF">You're not alone ..................</span></b>`)
mainWin = makeWin("Parent window for test")
// DialogNewWithButtons
dialog, err = gtk.DialogNewWithButtons("Dialog with buttons",
mainWin,
gtk.DIALOG_MODAL,
"Cancel",
"No",
"Maybe",
"Yes")
if ca, err := dialog.GetContentArea(); err == nil {
ca.PackStart(lbl, true, true, 0)
ca.ShowAll()
}
}
if err != nil {
log.Fatal("Unable to ... do what I …
```

 Add gtk_dialog_new_with_buttons() 

---

gtk/gtk.go

gtk_tree_path_get_depth()
gtk_tree_path_copy()
gtk_tree_path_compare()

add TreePath functions

---

gtk/gtk.go

gtk_tree_selection_unselect_range()
gtk_tree_selection_path_is_selected()

add TreeSelection functions

---

gtk/gtk_since_3_16.go

gtk_text_buffer_insert_markup()

add TextBuffer

---

gtk/gtk.go

gtk_text_buffer_remove_selection_clipboard()
gtk_text_buffer_add_selection_clipboard()
gtk_text_buffer_paste_clipboard()
gtk_text_buffer_cut_clipboard()
gtk_text_buffer_copy_clipboard()
gtk_text_buffer_get_insert()
gtk_text_buffer_deserialize()
gtk_text_buffer_serialize()
gtk_text_buffer_register_deserialize_tagset()
gtk_text_buffer_register_serialize_tagset()
gtk_text_buffer_remove_tag_by_name()
gtk_text_buffer_create_tag()
gtk_text_buffer_get_iter_at_line_offset()
gtk_text_buffer_get_selection_bounds()
gtk_text_buffer_get_selection_bound()
gtk_text_buffer_delete_selection()
gtk_text_buffer_get_has_selection()

add TextBuffer functions

---

gtk/gtk.go
gtk/text_iter.go

gtk_text_iter_forward_search()
gtk_text_iter_backward_search()
&
marshalTextSearchFlags and enum

 add TextIter search functions & childs

---

gtk/gtk_since_3_16.go

Add missing C #include in gtk_since_3_16.go

---

gtk/tree_view.go

TreeView:
gtk_tree_view_set_tooltip_row()
gtk_tree_view_set_tooltip_cell()

Add TreeView SetTooltipRow/Cell

---

gtk/tree_view.go

TreeView:
gtk_tree_view_is_blank_at_pos()

Add TreeView IsBlankAtPos

---

gtk/tree_view.go

proposal TreeView conforming to golang [GetPathAtPos](https://developer.gnome.org/gtk3/stable/GtkTreeView.html#gtk-tree-view-get-path-at-pos):
Hi,
The actual definition does not follow (in my opinion), the golang style implementation.
I would like to propose a modification to change it and keep the spirit of golang.
Considering the implications this may have for a code written previously, I would like to know your opinion.
If you think it's a good idea, merge it or not.
Note: PR (previous one) containing the "[IsBlankAtPos](https://developer.gnome.org/gtk3/stable/GtkTreeView.html#gtk-tree-view-is-blank-at-pos)" function do the same job (except the return bool) and follow the golang style. So my request is not essential, but rather a benefit.
Must be read by repository owners before doing …

proposal TreeView conforming GetPathAtPos

---

gtk/gtk.go

Conformation of gtk_dialog_new_with_buttons() to gtk3 official declaration:
A few months ago, I wrote this wrap for gtk_dialog_new_with_buttons().
Now, I just modified the implementation of the buttons to reflect more precisely the official documentation of gtk3.
From now on, the type of answer must correspond strictly to the official declaration and no longer as previously, automatically assigned in relation to the position of the button in the control.
- []interface{}{"Accept", gtk.RESPONSE_ACCEPT} is a better way to do than before.

conformation of gtk_dialog_new_with_buttons

---

gtk/gtk.go

TextBuffer:
gtk_text_buffer_get_iter_at_line_index()

Add TextBuffer GetIterAtLineIndex

---

gdk/gdk.go
gdk/window_x11.go

add gdk function
gdk_x11_window_foreign_new_for_display()
gdk_pixbuf_get_from_window()
gdk_window_get_height()
gdk_window_get_width()

add gdk function

---

gtk/gtk.go

Add-TreeStore
gtk_tree_store_insert_with_valuesv()

Add TreeStore InsertWithValues

---

gtk/tree_view.go

Add Treeview GetColumns:
gtk_tree_view_get_columns()

Add Treeview GetColumns

---

gtk/tree_view_column.go

TreeViewColumn GetButton:
gtk_tree_view_column_get_button()

Add TreeViewColumn GetButton

---

gtk/widget.go

adding support for gtk_widget_get_tooltip_markup() and gtk_widget_set_tooltip_markup().

add getter/setter bindings for TooltipMarkup

---

gtk/gtk.go

* gtk_file_chooser_select_filename
* gtk_file_chooser_unselect_filename
* gtk_file_chooser_select_all
* gtk_file_chooser_unselect_all

multiple bindings for FileChooser

---

gtk/gtk_since_3_12.go
gtk/gtk_since_3_12.go.h
gtk/gtk_since_3_22.go

* gtk_popover_bind_model
* gtk_popover_popup
* gtk_popover_popdown

Bindings for popover

---

gtk/gtk.go

Fixed issue with file dialogs not accepting nil parent windows

---

gtk/gtk.go

* gtk_toggle_button_toggled()
* gtk_toggle_button_get_inconsistent()
* gtk_toggle_button_set_inconsistent()
fixing wrong comment

adding togglebutton bindings

---

gtk/gtk.go

* gtk_color_button_set_title()
* gtk_color_button_get_title()

add getter/setter bindings for ColorButton title

---

gtk/gtk.go

* gtk_scale_button_set_value()
* gtk_scale_button_get_plus_button()
* gtk_scale_button_get_minus_button()

write bindings for ScaleButton

---

gtk/gtk.go
gtk/gtk.go.h

#503 Should be done afaik.
At least the TreeModelSort is working now :)

Tree model sort

---

gtk/gtk.go
gtk/gtk.go.h

I've abstracted the TreeSortable with ITreeSortable and a generic interface like TreeModel.
Would be great if someone could check this :)

Abstraction of GtkTreeSortable

---

gtk/gtk.go

Use native types directly

---

gdk/gdk.go

readding gdk_pixbuf_get_type()

---

gtk/gtk.go
gtk/gtk_since_3_10.go

commenting the ones with missing dependencies

added last bindings for GtkEntry

---

gtk/widget.go
gtk/window.go

exported getter for IWidget and IWindow

---

gtk/cell_area.go
gtk/cell_area_since_3_14.go
gtk/gtk.go
gtk/gtk.go.h

most bindings for
* GtkCellArea
all bindings for
* GtkCellAreaContext
* GtkCellAreaBox
added bindings for GtkDirectionType and GtkCellRendererState

Bindings for GtkCellArea, GtkCellAreaContext, GtkCellAreaBox, GtkDirectionType, and GtkCellRendererState

---

gdk/gdk.go
gtk/application.go
gtk/gtk.go
gtk/gtk_deprecated_since_3_24.go
gtk/window.go
gtk/windowgroup.go

is related to #369  
might fix it

check GList before wrapping it

---

gtk/gtk_since_3_10.go
gtk/text_view.go
pango/pango-layout.go
pango/pango.go

add bindings for PangoTabArray
* not included: TabArrayNewWithPositions(), GetTabs()
add GetTabs/SetTabs bindings for Entry
add GetTabs/SetTabs bindings for TextView
* fixes #497

support PangoTabArray

---

gdk/gdk_since_3_22.go

adding bindings for GdkMonitor

---

gdk/gdk.go
gdk/gdk.go.h
gdk/gdk_since_3_18.go
gtk/accel.go

bindings for
* gdk_keymap_translate_keyboard_state() 
* gdk_keymap_get_for_display()
* gdk_keymap_have_bidi_layouts()
* gdk_keymap_get_caps_lock_state()
* gdk_keymap_get_num_lock_state()
* gdk_keymap_get_modifier_state()
* for gdk_keymap_get_scroll_lock_state()
fixes #384

add GdkKeymap bindings

---

gdk/gdk.go

add hardware_keycode of C.GdkEventKey

C.GdkEventKey.hardware_keycode

---

gdk/pixbuf_since_2_2.go
glib/list.go
glib/slist.go
gtk/accel.go
gtk/gtk.go

removed `v.list = nil`, as it causes nilpointer exception
fixes  #563

added some missing datawrappings for where SList is used

---

gdk/gdk.go

Add the gdk_set_allowed_backends function.

add the gdk_set_allowed_backends function

---

.gitignore
gio/gresource.go
gio/gresource.go.h
gio/utils.go
go.mod
gtk/gtk.go
gtk/gtk_since_3_16.go

Added basic GResource methods:
**GTK**
* `gtk_css_provider_load_from_resource()`
**GIO**
- `g_resource_load()`
- `g_resource_new_from_data()`
- `g_resources_register()`
- `g_resources_unregister()`
- `g_resources_enumerate_children()`
Also added Go module for this library

CSS load from resource and add gresource_* functions

---

gtk/cell_area.go
gtk/cell_area_since_3_14.go
gtk/gtk.go

* and removed some unneeded parameters

 Use the ICellRenderer interface for CellArea & Co.

---

gtk/cell_area.go
gtk/gtk.go

fix for #578, which was still work in progress

wrong func call on ICellRenderer + missing cast

---

gtk/combo_box.go
gtk/gtk.go
gtk/icon_view.go
gtk/tree_view.go
gtk/widget.go
gtk/window.go

Getmodel: use the ITreeModel interface

---

gtk/gtk.go
pango/pango-font.go

- gtk_tree_store_prepend
- gtk_tree_store_move_before
- gtk_tree_store_move_after
- gtk_tree_store_swap

Add more bindings for GtkTreeStore.

---

glib/glib_test.go

* glib.GValue(STRING) + GetString()

WIP: writing some unittests

---

gdk/gdk_since_3_18.go

- gdk_window_set_pass_through
- gdk_window_get_pass_through

Add more bindings for GdkWindow

---

glib/gfile.go
gtk/app_chooser.go
gtk/application.go
gtk/color_chooser.go
gtk/gtk_since_3_20.go
gtk/print.go

plus adding Native() to GFile implementation, so that AppChooserDialogNew() works
fixes #593

fix segfaults on call to toWindow

---

.travis.yml

It was written to the file named '1' which I believe isn't how it's meant to be

Travis: fix Xvfb output redirection

---

gtk/gtk.go

Add gtk_file_filter_get_name()

---

gtk/gtk.go

add gtk_list_store_set_column_types()

Add ListStore.SetColumnTypes()

---

gtk/gtk.go

add gtk_tree_store_set_column_types)

Add TreeStore.SetColumnTypes()

---

gtk/gtk_since_3_10.go

Add gtk_icon_theme_load_icon_for_scale()

Add IconTheme.LoadIconForScale

---

gtk/gtk.go

Add IconTheme.HasIcon

---

gtk/gtk_export.go

Exported func: goTreeSelectionFunc

goTreeSelectionFunc

---

gtk/gtk.go.h

_gtk_tree_selection_set_select_function

_gtk_tree_selection_set_select_function

---

gtk/gtk.go

(*TreeSelection).TreeSelectionFunc: GtkTreeSelectionFunc
(*TreeSelection).SetSelectFunction: gtk_tree_selection_set_select_function()

Add TreeSelection Select function and definition.

---

gtk/gtk_since_3_16.go

gtk_text_view_set_monospace
gtk_text_view_get_monospace

Add TextView func 3.16

---

gtk/gtk.go

gtk_text_buffer_end_user_action
gtk_text_buffer_begin_user_action
gtk_text_buffer_delete_interactive
gtk_text_buffer_insert_range
gtk_text_buffer_insert_range_interactive
gtk_text_buffer_insert_interactive
gtk_text_buffer_insert_interactive_at_cursor

Add TextBuffer func

---

gtk/gtk.go

Updating methods that use GtkTextMark to work with new TextMark implementation.

Updating methods that use GtkTextMark

---

gtk/gtk.go

Update gtk.go with GtkImage methods using GIcon
gtk_image_new_from_gicon()
gtk_image_set_from_gicon()
gtk_image_get_gicon()

Update gtk.go with GtkImage methods using GIcon

---

gtk/gtk.go
gtk/gtk_since_3_18.go
gtk/text_child_anchor.go
gtk/text_child_anchor.go.h
gtk/text_view.go

File modified: 'text_child_anchor.go'
gtk_text_child_anchor_new
gtk_text_child_anchor_get_widgets
gtk_text_child_anchor_get_deleted
File modified: 'gtk_since_3_18.go'
gtk_text_view_set_top_margin
gtk_text_view_get_top_margin
gtk_text_view_set_bottom_margin
gtk_text_view_get_bottom_margin
File modified: 'text_view.go'
Removing TODO informations relative to added methods above.

Add binding for TextView & TextAnchor

---

gdk/gdk_since_3_10.go
gtk/widget.go
gtk/widget_since_3_10.go

This PR succeeds PR #689 to add GetScaleFactor bindings for HiDPI support.

Add get_scale_factor bindings

---

gdk/gdk.go

altered file: 'gdk.go'
gdk_rgba_copy, with newRGBAFromNative that handle Finalizer
gdk_rgba_equal
gdk_rgba_hash
gdk_rgba_free

Add bindings for GdkRGBA

---

gtk/gtk.go

Altered file: 'gtk.go'
GtkSpinButtonUpdatePolicy
GtkSpinType
gtk_spin_button_set_adjustment
gtk_spin_button_set_digits
gtk_spin_button_set_update_policy
gtk_spin_button_set_numeric
gtk_spin_button_spin
gtk_spin_button_update
gtk_spin_button_get_digits
gtk_spin_button_get_update_policy

Adding some GtkSpinButton methods and Types

---

glib/list.go

This commit adds the following functions:
(*glib.List).First() *glib.List
(*glib.List).Last() *glib.List
(*glib.List).Reverse() *glib.List

Add extra GList functions

---

gtk/gtk.go

Adding SetOrientation for gkt.SpinButton

Added SetOrientation to gkt.SpinButton

---

gtk/gtk.go

Implemented CellRenderer.SetAlignment which is a wrapper around gtk_tree_view_column_set_alignment()

Implemented CellRenderer.SetAlignment

---

gtk/menu_shell.go

gtk_menu_shell_bind_model()
gtk_menu_shell_get_parent_shell()
gtk_menu_shell_get_selected_item()
gtk_menu_shell_get_take_focus()
GtkMenuDirectionType / Marshaler

Add bindings GtkMenuShell

---

gtk/gtk.go

gtk_menu_item_set_reserve_indicator()
gtk_menu_item_get_reserve_indicator()
gtk_menu_item_toggle_size_allocate()
gtk_menu_item_toggle_size_request()
gtk_menu_item_activate()
gtk_menu_item_deselect()
gtk_menu_item_select()
gtk_menu_item_get_submenu()

Add GtkMenuItem bindings

---

gdk/gdk.go
gdk/gdk_since_3_20.go

- PointNew()
- GetPointInt()
- SetPointInt()
- GetX()
- SetX()
- GetY()
- SetY()
- gdk_rectangle_intersect()
- gdk_rectangle_union()
- gdk_rectangle_equal()
- SetRectangleInt()
- GetRectangleInt()
- RectangleNew()

Add bindings/helper methods GdkRectangle GdkPoint

---

gtk/gtk_since_3_18.go

gtk_radio_menu_item_join_group()

Add binding for GtkRadioMenuItem

---

glib/glib.go

This pull request fixes the compile errors caused by merging #706 after #743.

Fix GLib compile from merge conflicts

---

gtk/gtk.go
gtk/gtk_since_3_22.go

Hi, this is my first contribution, please review, any feedback welcome.
Solves #545

added missing ScrolledWindow methods

---

glib/gmain_context.go

This commit adds the following functions:
```go
func (v *glib.MainContext) Acquire()
func (v *glib.MainContext) Release()
func (v *glib.MainContext) IsOwner() bool
```

Add MainContext.{IsOwner,Acquire,Release}

---

glib/glib.go

Add glib.Value.Unset for unset manually.

Add binding for g_value_unset

---

glib/cast.go
gtk/gtk.go

Support casting glib classes

---

gdk/pixbuf_since_2_2.go

Fix for https://github.com/gotk3/gotk3/issues/791

Fix for #791 gdk.PixBufGetFormats() panics

---

cairo/pattern.go

Add cairo filter elements:
cairo_filter_t
cairo_pattern_set_filter()
cairo_pattern_get_filter()

Add cairo_filter_t and derived fncts

---

gtk/widget.go

Add wrappers for `gtk_widget_realize` and `gtk_widget_unrealize`

Implement widget un/realize wrappers

---

gtk/gtk.go
gtk/gtk_since_3_10.go
gtk/gtk_since_3_22.go

added some missing FileChooser methods

File chooser

---

gtk/gtk.go

add binding for:
gtk_file_chooser_set_action()
gtk_file_chooser_get_action()

Add (*gtk).FileChooser Set/GetAction

---

gdk/gdk.go

Add binding for SetOverrideRedirect
responding to #858

Add binding for SetOverrideRedirect

---

gdk/gdk.go

Adding all GdkEventTouch bindings except axes and sequence.

Gdk event touch

---

gdk/gdk_since_3_22.go

Maps all the functions and consts I could find for Seats. It seems to work in my testing although I've not used any of the callbacks, so they could be wrong when used.
Reference: https://docs.gtk.org/gdk3/class.Seat.html

Implementing most of Gdk Seats

---

gdk/gdk_since_3_22.go

Fixes https://github.com/gotk3/gotk3/issues/930

Fixing undefined: callback
