- gdk/gdk.go
- gtk/gtk_deprecated_since_3_16.go
https://developer.gnome.org/gdk3/stable/GdkDisplay.html#gdk-display-supports-composite
> gdk_display_supports_composite() has been deprecated since version 3.16

- gtk/gtk.go
It does not need an instance of GtkCssProvider.
> Refactor gtk_css_provider_get_default() 

- gtk/gtk.go
Since they receive interface params, you cant pass nil and call toWidget()
> Refactor functions that accept nil widgets as parameters

- glib/glib.go
- gtk/gtk.go
Although `RefSink` behaves like `Ref` for non floating objects, we should only sink references on floating objects.
Thoughts?
> Makes wrapObject use the appropriate ref increasing method

- glib/glib.go
It errors on some singnal handlers due having double `SetFinalizer()` call.
> Remove unecessary finalizers on GValue

- gtk/gtk_since_3_10.go
Using builder.GetObject() with a GtkHeaderBar causes a error because GtkHeaderBar's wrap function was not added to WrapFn.
> Added GtkHeaderBar to WrapFn

- gtk/accel.go
- gtk/gtk.go
- gtk/gtk_deprecated_since_3_14.go
- gtk/gtk_since_3_10.go
- gtk/style.go
- gtk/tree_view.go
- gtk/tree_view_column.go
- gtk/widget.go
- gtk/window.go
- pango/pango-context.go
- pango/pango-layout.go
This will enable GC-ing GTK pointers through finalizers on every object. I've been testing this for some time with no problems.
> Use wrapObject all over

- gdk/gdk.go
- glib/list.go
- glib/list_test.go
- gtk/gtk.go
Trying to simplify interface for retrieving glib.List elements when gtk returns one. Added `dataWrap` function field to glib.List and methods `NthDataWrapped` and `DataWrapped`, which call that function to wrap raw data into Go types.
The wrapper has to be specified during List initialization...
```
glist.DataWrapper(func(ptr unsafe.Pointer) interface{} {
return &TreePath{(*C.GtkTreePath)(ptr)}
})
```
...to ease getting List's data into this
```
path := l.NthDataWrapped(i).(*gtk.TreePath)
```
I thought about more universal way of casting raw Gtk+ data into Go types. E.g. there's a large `WrapMap`, defined in gtk.go. But some GTK+ values are not GObjects (GtkTreePath is not), therefore their type cannot be determined during runtime for automatic casting.
**Todo:** may be, remove NthData() …
> Wrap glib.List elements

- cairo/translations.go
This pathc adds basic translation wrappers to cairo. Once cairo_matrix_t has been covered, cairo translations can easily be completed.
> Added translations to cairo.

- gtk/gtk.go
The buffer is allocated as per https://developer.gnome.org/gtk3/stable/GtkTextBuffer.html#gtk-text-buffer-get-text
> gtk_text_buffer_get_text result needs to be freed

- gtk/gtk.go
I hit this panic.
```
panic: interface conversion: interface is *gtk.TreePath, not gtk.TreePath
goroutine 4 [running]:
panic(0xbb93a0, 0xc820368040)
/usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/pekim/mixlac-go/vendor/github.com/gotk3/gotk3/gtk.(*TreeSelection).GetSelectedRows.func2.1(0xbe26c0, 0xc82013a018)
/home/mike/go/src/github.com/pekim/mixlac-go/vendor/github.com/gotk3/gotk3/gtk/gtk.go:8299 +0x4c
github.com/pekim/mixlac-go/vendor/github.com/gotk3/gotk3/glib.(*List).Foreach(0xc8203eedd0, 0xeb9f30)
/home/mike/go/src/github.com/pekim/mixlac-go/vendor/github.com/gotk3/gotk3/glib/list.go:146 +0x58
github.com/pekim/mixlac-go/vendor/github.com/gotk3/gotk3/glib.(*List).FreeFull(0xc8203eedd0, 0xeb9f30)
/home/mike/go/src/github.com/pekim/mixlac-go/vendor/github.com/gotk3/gotk3/glib …
```
> Correct type in GetSelectedRows finalizer.

- gtk/gtk.go
For some reason (it was forgotten?) GtkColorButton did not have its wrapping function in WrapMap. This PR should fix issue #113. As far as I could see, all other wrapping functions were already in WrapMap.
> Add GtkColorButton to WrapMap

- gtk/gtk.go
When creating a radio button, or setting its group, we should be able to use a nil reference.
This allow creating the first button when we still don't have the group, or unsetting the group of a button.
> gtk.RadioButton and RadioMenuItem: Allow usage of nil group pointers.

- gtk/gtk.go
An example has been added to gotk3-examples (stack) to test this.
I could merge those directly, but I prefer having a review.
> Fix crash when using Container.ChildSetProperty.

- gtk/gtk.go
- gtk/gtk.go.h
Only supports filtering by a column.
`gtk_tree_model_filter_set_visible_func` looked too scary to implemented. So I stuck with the minimum that would meet my current needs.
> Add support for TreeModelFilter.

- gdk/gdk.go
This is for when a *Event represents a GdkEventKey.
Like I say in the doc for `EventKeyNewFromEvent`, this facilitates something like this.
```go
window.Connect("key-press-event", func(_ *gtk.Window, event *gdk.Event) {
eventKey := gdk.EventKeyNewFromEvent(event)
fmt.Println(eventKey.KeyVal(), eventKey.State())
})
```
Perhaps there's a way of achieving this without creating a function like this?
> Add a function to create *EventKey from a *Event.

- gdk/gdk.go
For use when returning from an event handler where control of event propagation is required.
Example usage.
```go
window.Connect("key-press-event", func(_ *gtk.Window, event *gdk.Event) bool {
eventKey := gdk.EventKeyNewFromEvent(event)
if eventKey.KeyVal() == ... {
// handle the event in some way
return gdk.GDK_EVENT_STOP
}
return gdk.GDK_EVENT_PROPAGATE
})
```
> Add event propagation constants.

- gtk/gtk.go
- gtk/gtk_since_3_10.go
Added support for [`gtk_grid_remove_row`](https://developer.gnome.org/gtk3/stable/GtkGrid.html#gtk-grid-remove-row) and [`gtk_grid_remove_column`](https://developer.gnome.org/gtk3/stable/GtkGrid.html#gtk-grid-remove-column) methods, which are added to gtk3 since 3.10.
> Add support for gtk_gird_remove_row/column and gtk_container_child_get_property

- gdk/gdk.go
Added wrapper functions for [`gdk_unicode_to_keyval`](https://developer.gnome.org/gdk3/stable/gdk3-Keyboard-Handling.html#gdk-unicode-to-keyval) and [`gdk_keyval_to_unicode`](https://developer.gnome.org/gdk3/stable/gdk3-Keyboard-Handling.html#gdk-keyval-to-unicode).
These functions can be used in `key-press-event` signal to determine whether the pressed key is a printable character (`gdk_keyval_to_unicode(keyval) != 0`)
> Add support for gdk: unicode_to_keyval and keyval_to_unicode

- LICENSE
Fix ISC LICENSE, change 'and' to 'and/or', to avoid confusion
Read: https://en.wikipedia.org/wiki/ISC_license
I also think you change change `2013-2014` to `2013-2016`
> Fix ISC LICENSE, change 'and' to 'and/or', to avoid confusion

- gtk/gtk_since_3_10.go
Added a newline between the two comments so `* GtkGrid` does not show up in the documentation.
before: https://godoc.org/github.com/gotk3/gotk3/gtk#Grid.RemoveRow
after: https://godoc.org/github.com/reujab/gotk3/gtk#Grid.RemoveRow
> Fixed documentation error.

- glib/application.go
This leads to a segfault. And seems to have no meaning.
> Do not call set_string on NULL pointer in g_application_run wrapper

- gtk/widget_since_3_14.go
This adds both the wrappers for gtk_widget_get_clip and gtk_widget_set_clip.
> gtk: add gtk 3.14 widget functions

- gdk/gdk.go
Copy pasted code from EventKeyNewFromEvent for easier use of events. Needed access to gdk.EventButton from a gdk.Event and wanted an easier way to do it. Not going to lie only partial understand whats going on (as I haven't programmed gtk in c or c++ ever)
> Added EventXXXNewFromEvent for Event types

- cairo/canvas.go
- gtk/gtk.go.h
- gtk/print.go
- gtk/print_since_3_16.go
- gtk/print_test.go
- pango/pango-context.go
- pango/pango-layout.go
- pango/pango-types.go
Add nearly complete wrappers for GtkPageSetup, GtkPaperSize, GtkPrintContext, GtkPrintOperation, GtkPrintOperationPreview, GtkPrintSettings and GtkPrintContext. Basically the functions with callbacks are missing.
> Add wrappers for some printing related functions.

- gtk/gtk.go
Hi,
I'm working on a toy project that needs the wrapper to gtk_scale_set_draw_value(); since I didn't find it, I just added it; hopefully it can be merged if anybody else needs it.
Thanks,
Andrea
> added wrapper around gtk_scale_set_draw_value

- gtk/gtk_export.go
The address of `model *C.GtkTreeModel` that I received as parameter still in use in other places so unreferring it is causing trouble.
> Unreferring address that still in use is causing trouble 

- gtk/text_view.go
Was not returning the iter that had been passed to the
gtk_text_view_get_iter_at_... function.
> Return populated GtkTextIter from TextView.GetIterAt... functions.

- glib/settings.go
Implement SetStrv, but doesn't compile. Please help fix. The documentation of the function is here https://developer.gnome.org/gio/stable/GSettings.html#g-settings-set-strv. I have opened a question in StackOverflow (https://stackoverflow.com/questions/47907238/convert-glib-c-method-with-string-array-as-parameter-to-go), but nobody answered. I don't have enough knowledge of C to do this.
> Added SetStrv to glib.settings

- gtk/gtk.go
Add support for `SetMode()`,`GetMode()` on `ToggleButton` for `CheckButton`, `RadioButton` to disable `drawIndicator` property with. This lets a group of `RadioButtons` appear like a `StackSwitcher` by reverting their display back to the pressed/depressed button.
This relates to #228
> Add support for SetMode(),GetMode() on ToggleButton

- glib/application.go
- glib/gaction.go
- glib/gactiongroup.go
- glib/gactionmap.go
- glib/glib.go.h
- glib/gsimpleactiongroup.go
- glib/gvarianttype.go
- gtk/application.go
- gtk/application_window.go
- gtk/gtk.go
- gtk/gtk.go.h
- gtk/widget.go
This PR implements types/functions related to actions. I got carried away when implementing the necessary pieces for GAction...
Including:
* glib.Action (interface)
* glib.SimpleAction
* glib.PropertyAction
* glib.ActionGroup (interface)
* glib.ActionMap (interface)
* glib.SimpleActionGroup
* gtk.Widget.InsertActionGroup
* implementations of the interfaces where possible
This PR builds upon my previous PR #230 as SetMenuModel is necessary for the example to work.
Next steps still open: Implement GActionable to allow actions on more or less any widget.
This is a working example:
As you can see, at some points ugly magic like `&customActionGroup.ActionGroup` is required to make everything work. If there are any suggestions to make this look better, don't hold back!
Is the repo …
> Implement GAction and related types

- gtk/gtk.go
I am playing around with go and I am trying to implement a responsive UI where I need to insert large amounts of rows into a TreeView/ListStore. Scouring the Internet on how to achieve that I found several recommendations to use gtk_list_store_insert_with_values, which was not yet implemented in gotk3.
I have implemented the missing InsertWithValues wrapper by using gtk_list_store_insert_with_valuesv (instead of the varargs one). Keep in mind this is me touching go and cgo pretty much for the first time ever, so maybe you should take a closer look at it and tell me if my approach is correct.
I also added missing constants in this pull request as well, these are for setting a ListStore to unsorted or to sort by the default column. Setting a ListStore to unsorted is related to my problem of …
> Implement InsertWithValues and add missing constants to make ListStore unsorted/sort by default column.

- gtk/tree_view_column.go
Wanted to set column to GTK_TREE_VIEW_COLUMN_FIXED, needed to implement wrapper for gtk_tree_view_column_set_sizing for that. Implemented wrapper for gtk_tree_view_column_set_sizing as well while I was at it.
> Implement Set/GetSizing() wrappers for gtk_tree_view_column_set/get_sizing()

- gtk/gtk_deprecated_since_3_8.go
Adds support for the opacity-related functions.
For the Window type they are only added for 3.6, since they have been superseded by the related functions on Widget type with gtk 3.8.
Fixes gotk3/gotk3#212 and fixes gotk3/gotk3#213
> Add {Get,Set}Opacity for Widget (since 3.8) and Window (deprecated, only added gtk<3.8)

- glib/application.go
- glib/gactiongroup.go
- glib/gactionmap.go
- glib/gsimpleactiongroup.go
- glib/gsimpleactiongroup_test.go
- gtk/application.go
- gtk/application_window.go
To avoid duplication of glib.Object functions when embedding ActionGroup and ActionMap in other types, this is the solution approach I outlined in #232.
In addition, this PR adds:
* Basic unit testing for SimpleActionGroup
Fixes #232 and fixes #249
> Embed interfaces instead of structs for ActionGroup and ActionMap

- gtk/gtk.go
- gtk/gtk_since_3_12.go
- gtk/stack_since_3_12.go
Includes:
* Entry.{Get,Set}MaxWidthChars() in proper location ( supersedes and closes #202 )
* Dialog.GetHeaderBar()
* GtkTextDirection enum (not added in 3.12, but required for one of the functions)
* GetLocaleDirection()
* HeaderBar.{Get,Set}DecorationLayout()
* HeaderBar.{Get,Set}HasSubtitle()
* MenuButton.{Get,Set}UsePopover()
* Stack.GetTransitionRunning()
> Add several missing functions added in GTK 3.12

- gtk/widget.go
It is currently not possible to pass a SimpleActionGroup to InsertActionGroup, because it only takes the ActionGroup concrete type.
> Let InsertActionGroup take IActionGroup.

- cairo/surface.go
I am working on a binding for librsvg. One common use case is to use librsvg + Cairo to convert SVGs to various other formats. This commit adds the `WriteToPNG` method to `Surface`.
The cairo package currently already assumes that PNG support is built in (per `NewSurfaceFromPNG`).
> Add a wrapper around cairo_surface_write_to_png.

- cairo/canvas.go
- cairo/surface.go
PDF surfaces and associated contexts should be closed properly or they
will result in an empty or otherwise invalid PDF file. Since finalizers
are not guaranteed to run in Go, an explicit Close() method is required
to guarantee the proper closure of contexts and surfaces.
> Add a constructor for creating PDF surfaces.

- gtk/tree_view_column.go
Implemented bindings for the gtk_tree_view_column_get/set_sort_order and created a type for GtkSortType so that the direction of a sort indicator on a treeview column can be toggled.
Contains a small fix to use TreeViewColumnSizing type in the const declaration for the treeview column sizings instead of just int.
> Implement gtk_tree_view_column_get/set_sort_order

- gtk/tree_view_column.go
I had not noticed that there already was a type declaration for GtkSortType and created a duplicate declaration by accident. This commit removes the duplicate and instead uses the previously declared one.
> fix remove duplicate declaration of const GtkSortType

- gtk/shortcutswindow_since_3_22.go
- gtk/shortcutswindow_since_3_22.go.h
Added `ShortcutsWindow` type.
Example:
```GO
package main
import (
"github.com/gotk3/gotk3/gtk"
)
func main() {
gtk.Init(nil)
builder, _ := gtk.BuilderNew()
//Add file content as multilinestring: http://gitlab.gnome.org/GNOME/gtk/raw/gtk-3-22/demos/gtk-demo/shortcuts-gedit.ui
builder.AddFromString(...)
window, _ := builder.GetObject("shortcuts-gedit")
windowCast, ok := window.(*gtk.ShortcutsWindow)
if ok {
windowCast.SetResizable(true)
windowCast.ShowAll()
} else {
panic("Invalid type")
}
gtk.Main()
}
```
This is my 2. attempt, I already had a "fucked up" PR, which I closed: https://github.com/gotk3/gotk3/pull/291
Hope I didn't get it wrong, but afaik it has been added in 3.22, at least according to the commit: https://github.com/GNOME/gtk/commit/1dfbae1aa41bb2b3b95fa841e0c1707fab52ca8b …
> Add bindings for GtkShortcutsWindow

- .travis.yml
- glib/menu.go
`g_menu_{insert,prepend,append}_section` allows `label` to be `NULL` as a way to create an unlabeled section within a menu. Since go strings cannot be nil, creating unlabeled sections is currently not possible. This pull request adds new `glib.Menu` methods `InsertSectionWithoutLabel`, `PrependSectionWithoutLabel`, and `AppendSectionWithoutLabel` to allow adding unlabeled sections to a `glib.Menu`.
> Add glib.Menu.*SectionWithoutLabel() for unlabeled menu sections.

- gtk/gtk.go
- gtk/text_child_anchor.go
- gtk/text_view.go
Wrap `GtkTextChildAnchor`, `gtk_text_buffer_create_child_anchor`, `gtk_text_view_add_child_at_anchor`.
---
The `iter` passed to `TextBuffer.CreateChildAnchor` is mangled in this call chain:
`gtk_text_buffer_create_child_anchor` at [gtktextbuffer.c:2024](https://gitlab.gnome.org/GNOME/gtk/blob/3.22.30/gtk/gtktextbuffer.c#L2024)
`g_signal_emit`
`g_signal_emit_valist`
`_g_closure_invoke_va`
`_gtk_marshal_VOID__BOXED_OBJECTv` at [gtkmarshalers.c:3131](https://gitlab.gnome.org/GNOME/gtk/blob/3.22.30/gtk/gtkmarshalers.c#L3131)
`gtk_text_buffer_real_insert_anchor` at [gtktextbuffer.c:1962](https://gitlab.gnome.org/GNOME/gtk/blob/3.22.30/gtk/gtktextbuffer.c#L1962)
`_gtk_text_btree_insert_child_anchor` at [gtktextbtree.c:1335](https://gitlab.gnome.org/GNOME/gtk/blob/3.22.30/gtk/gtktextbtree.c#L1335 …
> Add TextChildAnchor, TextBuffer.CreateChildAnchor, TextView.AddChildAtAnchor

- gtk/gtk.go
- gtk/gtk_deprecated_since_3_16.go
- gtk/gtk_deprecated_since_3_24.go
- gtk/gtk_since_3_20.go
- gtk/label.go
Current build process produce list of deprecated warnings:
```bash
[ddyakov@archlinux_dd2 gotk3]$ go build -v ./...
github.com/ddkv/gotk3/gtk
cgo-gcc-prolog: In function ‘_cgo_9f28af190df4_Cfunc_gtk_container_get_focus_chain’:
cgo-gcc-prolog:2964:2: warning: ‘gtk_container_get_focus_chain’ is deprecated [-Wdeprecated-declarations]
In file included from /usr/include/gtk-3.0/gtk/gtkbin.h:33,
from /usr/include/gtk-3.0/gtk/gtkwindow.h:35,
from /usr/include/gtk-3.0/gtk/gtkdialog.h:32,
from /usr/include/gtk-3.0/gtk/gtkaboutdialog.h:30,
from /usr/include/gtk-3.0/gtk/gtk.h:31,
from gtk/gtk.go:48:
/usr/include/gtk-3.0/gtk/gtkcontainer.h:180:10: note: declared here
gboolean gtk_container_get_focus_chain  (GtkContainer   *container,
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cgo-gcc-prolog: In function …
```
> Sync functions deprecated since 3.16, 3.24 with corresponding build tags

- gtk/gtk.go
- gtk/widget.go
I added some simple additional wrappers. The functions are:
* TextBuffer.GetMark around gtk_text_buffer_get_mark
* TextBuffer.RemoveAllTags around gtk_text_buffer_remove_all_tags
* Interface TreeSortable as a wrapper around GtkTreeSortable
* TreeStore.SetSortColumnId as an implementation of the interface TreeSortable and a wrapper around gtk_tree_sortable_set_sort_column_id
* Entry.RemoveIcon as a wrapper around gtk_entry_set_icon_from_icon_name. There is a wrapper around this function already. The existing wrapper does not allow to delete an icon (once placed). A nil pointer to a string allows such functionality in C. Since the existing function is probably used by someone I rather implemented a new function to provide the missing functionality.
* FreezeChildNotify as a wrapper around …
> Ext2019 02

- gdk/gdk.go
I added a wrapper for the GdkEventConfigure, similar to the other already wrapped events (e.g. GdkEventWindowState): 
- a new struct EventConfigure
- new constructors EventConfigureNew and EventConfigureNewFromEvent
- X(), Y(), Width(), and Height() to provide access to the payload of a GdkEventConfigure
> add support for GdkEventConfigure

- gtk/widget.go
usage example:
evBox, _ := gtk.EventBoxNew()
t_uri, _ := gtk.TargetEntryNew("text/uri-list", gtk.TARGET_OTHER_APP, 0)
evBox.DragSourceSet(gdk.GDK_BUTTON1_MASK, []gtk.TargetEntry{*t_uri}, gdk.ACTION_COPY)
> C.gtk_drag_source_set

- gtk/gtk.go
look there https://github.com/gotk3/gotk3/issues/327
and pull THIS first https://github.com/gotk3/gotk3/pull/328
usage example:
t_uri, _ := gtk.TargetEntryNew("text/uri-list", gtk.TARGET_OTHER_APP, 0)
evBox.DragSourceSet(gdk.GDK_BUTTON1_MASK, []gtk.TargetEntry{*t_uri}, gdk.ACTION_COPY)
evBox.Connect("drag-begin", func(g *gtk.EventBox, ctx *gdk.DragContext) {
fmt.Println("drag-begin")
pixbuf := .....
gtk.DragSetIconPixbuf(ctx, pixbuf, 0, 0)
})
evBox.Connect("drag-data-get", func(g *gtk.EventBox, ctx *gdk.DragContext, data_pointer uintptr, _ uint, _ uint) {
fmt.Println("drag-data-get")
cmd := "file://" + "/mnt/dm-1/testfile.txt" + "\n"
gtk.SetData(data_pointer, gdk.SELECTION_TYPE_STRING, []byte(cmd))
})
> gtk_selection_data_set & gtk_drag_set_icon_pixbuf

- gdk/window_x11.go
To embed movies in my app using libvlc, I need to get the XID for a gtk.DrawingArea to pass to libvlc.
Sequence is get the gdk window from a widget, then use this new function to get the underlying X window from the gdk window.
Tested with libvlc - movie played correctly.
> Add wrapper gdk.GetXID for gdk_x11_window_get_xid

- gtk/gtk.go
This PR implements https://developer.gnome.org/gtk3/stable/GtkTextBuffer.html#gtk-text-buffer-insert-pixbuf
> Implement gtk_text_buffer_insert_pixbuf

- pango/fontconfig.go.h
- pango/pango-font.go
I was reported: 
```
../gotk3/gotk3/pango/fontconfig.go.h:5:73: warning: passing 'char *' to parameter of type 'const
FcChar8 *' (aka 'const unsigned char *') converts between pointers to integer types with different sign
[-Wpointer-sign]
```
as 'FcConfigAppFontAddFile' takes an unsigned char: https://gitlab.freedesktop.org/fontconfig/fontconfig/blob/master/fontconfig/fontconfig.h#L449
This hopefully fixes it.
> Fix sign of passing parameter

- gtk/gtk.go
Allows getting the correct TreeIter for the underlying model from a valid TreeIter for a filter model
>  Add support for gtk_tree_model_filter_convert_iter_to_child_iter

- gtk/gtk.go
Tested in a small app by deleting multiple rows from a ListStore after selecting them in a TreeView. TreeRowRef is the standard pattern for this, as TreePaths change meaning if rows before them are deleted.
> Add support for GtkTreeRowRef

- gtk/combo_box.go
- gtk/icon_view.go
- gtk/tree_view.go
Fixes issue #358 by checking the model parameter is not nil before trying to call its toTreeModel(). Fix for ComboBox and TreeView as well as IconView. TreeView had an older fix coded a different way (involving two calls to gtk_tree_view_set_model.) I modified that function so that all three SetModel implementations are consistent. I didn't modify any other places where toTreeModel() is called because those were all contexts were nil/NULL is not allowed, so the panic is OK.
> Fix for issue #358 - Can't set an iconview model to nil

- gtk/gtk.go
- gtk/gtk.go.h
- gtk/gtk_export.go
* Add TreeModelFilter.ConvertPathToChildPath - wrapper for gtk_tree_model_filter_convert_path_to_child_path
* Add support for TreeModelFilter.SetVisibleFunc - wrappers for gtk_tree_model_filter_set_visible_func and  gtk_tree_model_filter_refilter + implementation of a filter func registry modeled on existing registries.
> Additional support for TreeModelFilter

- glib/glib.go
This is the fix for issue #361. The root cause was that signal parameters representing objects are
passed to the marshaler that's going to actually call the signal handler wrap the object in a generic one.
In C applications, the marshaler `g_cclosure_marshal_VOID__VOID` unwraps the object before calling the signal handler. Added code to glib.goMarshal to do this unwrapping.
Here's a small program to show the fix. Without the fix, the program panics when you hit the enter key in the Entry (can't convert *Object to *Entry.) With the fix, everything works, and the contents of the Entry are printed.
```go
package main
import (
"fmt"
"os"
"github.com/gotk3/gotk3/gtk"
)
func fatal(format string, args ...interface{}) {
fmt.Printf(format, args...)
os.Exit(1)
}
func main() {
gtk.Init(nil)
w, err …
```
> Issue361 marshal object

- gtk/gtk.go
- gtk/gtk.go.h
Please could you merge this wrapper. As cgo does not support functions with variable-argument lists (see https://github.com/golang/go/issues/975), I have created a wrapper with only one tag as I found it useful for my needs (same approach has been applied in go-gtk).
> InsertWithTag() is a wrapper around gtk_text_buffer_insert_with_tags() that supports only one tag

- gtk/gtk.go
- gtk/gtk.go.h
Please could you merge this wrapper. As cgo does not support functions with variable-argument lists (see golang/go#975), I have created a wrapper with only one tag as I found it useful for my needs.
> InsertWithTagByName() is a wrapper around gtk_text_buffer_insert_with _tags_by_name() that supports only one tag

- gtk/gtk.go
- gtk/gtk.go.h
- gtk/gtk_export.go
I need to keep a list of metadata about files sorted in the same order as in a gtk.ListStore, using filename as the sort key. The filenames contain special characters (e.g. [, {, etc.) The GTK sort algorithm uses
a collating sequence for en_US that isn't documented and doesn't match what I can get from using
golang.org/x/text collation. 
Even if I could emulate GTK sort, they could change the algorithm in a later version, so I want to use my collation sequence for both my metadata and the ListStore. I've wrapped gtk_tree_sortable_set_sort_func in a generic way for *C.GtkTreeSortable and then call the generic function from (*gtk.ListStore).SetSortFunc. This should make it easy for others to wrap SetSortFunc for other types implementing the GtkTreeSortable interface.
> Wrap gtk_tree_sortable_set_sort_func() for gtk.ListStore

- gtk/app_chooser.go
- gtk/application.go
- gtk/color_chooser.go
- gtk/gtk.go
- gtk/gtk_since_3_20.go
- gtk/print.go
Allows using *gtk.ApplicationWindow and other "subclasses" of windows
> Use gtk.IWindow instead of *gtk.Window

- gtk/gtk.go
- gtk/gtk.go.h
I used this cell renderer to render progress bars on a tree view. So I attached the cell renderer to a tree column (and then the tree view).
```
rendererProgress, err := CellRendererProgressNew()
treeColumn, err := TreeViewColumnNewWithAttribute("column title", rendererProgress, "value", columnNumber)
```
Now the column can render values [0,100] into the appropriate progress bar.
> adds wrapper for GtkCellRendererProgress

- gdk/gdk.go
Added `GdkEventCrossing` support, which is most of the time used to known when a user mouse over or leave a widget. Used in conjuction with `enter-notify-event` and `leave-notify-event` signals (which are already supported).
Gdk definition for `GdkEventCrossing`: https://github.com/linuxmint/gtk/blob/master/gdk/gdkevents.h#L831
Simple test if you want to check that it's working:
```
_, _ = window.Connect("leave-notify-event", func(w interface{}, e *gdk.Event) {
event := gdk.EventCrossingNewFromEvent(e)
fmt.Println(fmt.Sprintf("x=%v; y=%v; x_root=%v; y_root=%v; state=%v; time=%v; type=%v; mode=%v; detail=%v; focus=%v", event.X(), event.Y(), event.XRoot(), event.YRoot(), event.State(), event.Time(), event.Type(), event.Mode(), event.Detail(), event.Focus()))
})
```
When your mouse leave the …
> Add gdk.EventCrossing mapping of GdkEventCrossing

- gtk/widget_since_3_20.go
Added `gtk_widget_get_focus_on_click()` and `gtk_widget_set_focus_on_click` mapping according to: https://developer.gnome.org/gtk3/stable/GtkWidget.html#gtk-widget-set-can-focus
**Please read carefully**: I feel like i've understood how `deprecated` and `since` works but for good measure double check that i haven't made any mistake on this.
I wanted to add functions that are available on Widget from gtk 3.20 and above
> gtk_widget_get_focus_on_click and gtk_widget_set_focus_on_click

- gtk/gtk_since_3_14.go
This adds all the ListBox and ListBoxRow methods added in GTK 3.14, except for `gtk_list_box_selected_foreach()`, in a new `gtk_since_3_14.go` file. I hope I've got everything in the right place.
> Add ListBox and ListBoxRow methods from GTK 3.14

- gdk/gdk.go
The state of the modifier keys is available in the native event. It is useful to have different scrolling behavior depending on the pressed modifier keys.
> provide state of modifier keys for EventScroll

- gtk/gtk.go
Add MessageDialog:
gtk_message_dialog_get_message_area()
Hi, I leave a piece of code to quickly test the function:
```
package main
import (
"log"
"github.com/gotk3/gotk3/glib"
"github.com/gotk3/gotk3/gtk"
)
func main() {
var msgDialog *gtk.MessageDialog
var err error
var box *gtk.Box
var lbl *gtk.Label
var mainWin *gtk.Window
gtk.Init(nil)
if lbl, err = gtk.LabelNew(""); err == nil {
lbl.SetMarkup(`<b><span foreground="#A40000FF">Inside the GtkBox</span></b>`)
mainWin = makeWin("Parent window for test")
msgDialog = gtk.MessageDialogNew(mainWin,
gtk.DIALOG_MODAL,
gtk.MESSAGE_INFO,
gtk.BUTTONS_OK,
"")
msgDialog.SetTitle("Message dialog test")
msgDialog.SetProperty("text", "primary text")
msgDialog.SetProperty("secondary-text", "secondary text")
// GetMessageArea
if box, err = …
```
> Add gtk_message_dialog_get_message_area()

- gtk/combo_box.go
* gtk_combo_box_get_entry_text_column
* gtk_combo_box_set_entry_text_column
* gtk_combo_box_get_id_column
* gtk_combo_box_set_id_column
all are since 3.0 and earlier
> adding missing bindings for GtkComboBox: entry_text_column and id_column

- gtk/gtk.go
* gtk_entry_completion_new()
* gtk_entry_completion_set_model()
* gtk_entry_completion_get_model()
* gtk_entry_completion_set_minimum_key_length()
* gtk_entry_completion_get_minimum_key_length()
* gtk_entry_completion_set_text_column()
* gtk_entry_completion_get_text_column()
* gtk_entry_completion_set_inline_completion()
* gtk_entry_completion_get_inline_completion()
* gtk_entry_completion_set_popup_completion()
* gtk_entry_completion_get_popup_completion()
* gtk_entry_completion_set_popup_set_width()
* gtk_entry_completion_get_popup_set_width()
all of them are before gtk version 3.0
> adding various missing EntryCompletion bindings

- gdk/gdk_since_3_22.go
GetPrimaryMonitor does not always return a monitor if primary not
defined, add bindings to be able to get the monitor using other means.
Adds wrappers for:
* gdk_display_get_monitor()
* gdk_display_get_monitor_at_window()
* gdk_display_get_monitor_at_point()
> add more get_monitor_* bindings

- gtk/tree_view.go
bindings for
* gtk_tree_view_get_cell_area()
* gtk_tree_view_convert_widget_to_bin_window_coords()
* gtk_tree_view_convert_bin_window_to_widget_coords()
> adding treeview bindings (GetCellArea + funcs for coords conversion)

- gtk/gtk_deprecated_since_3_16.go
fix gtk_since_3_16.go:158:8: could not determine kind of name for C.free
> fix could not determine kind of name for C.free

- gdk/gdk.go
- gdk/gdk.go.h
- gtk/gtk.go
GDK:
gdk.go.h:
- static GdkPixbufAnimation * declarationn  64-68
gdk.go: 
- RegisterGValueMarshalers  
- New PixbufAnimation structure declaration with native, NativePrivate, marshalPixbufAnimation
- gdk_pixbuf_animation_new_from_file()  
- gdk_pixbuf_loader_get_animation()    
Convenient function like for Pixbuf. Write data, close loader return pixbufAnimation.
- func (v *PixbufLoader) WriteAndReturnPixbufAnimation
> Pixbuf animation

- gtk/gtk.go
- gtk/gtk.go.h
- gtk/gtk_export.go
- Better performance than gtk.Selection.GetSelectedRows on very large entries (>15k).
- Plus, Iters and Paths are directly accessible without using glibList
> Tree selection selected for each function

- gtk/socket_plug.go
- gtk/socket_plug.go.h
Should close #465. Didn't have an opportunity to really test GdkPlug but GdkSocket works properly, using this I was able to embed matchbox-keyboard in my app.
> support for GdkSocket and GdkPlug

- .travis.yml
- gtk/glarea.go
This PR utilizes all ubuntu distributions available on travis to cover more versions of gtk.
Also removes/replaces some obsolete bits, adds more golang versions and fixes a build issue on go 1.9 and lower in glarea.go.
> Travis build using multiple gtk versions

- gtk/socket_plug.go
closes #471 
GtkSocket and GtkPlug work only on linux, other parts of GTK are not reliant on these widgets, so just ignore them if not on linux.
> socket and plug are reliant on X11, build it only on linux

- glib/gfile.go
- glib/gicon.go
- glib/glib.go.h
- glib/notifications.go
GIcon needed minimal support for GFile
GFile uses a Go string to resolve the path
Implemented `Notification.SetIcon(path string)`
Tested on Elementary OS 5.1
> Added support for GIcon

- gtk/gtk.go
* gtk_link_button_get_visited()
* gtk_link_button_set_visited()
fixes #488
> add getter/setter bindings for LinkButton “visited” property

- gtk/combo_box.go
if the combobox contains an Entry, it is returned
otherwise, it returns an error.
In case of doubt: use in conjunction with gtk_combo_box_get_has_entry()
without this convenience func, getting the Entry within a ComboBox is rather ugly
> convenience func ComboBox.GetEntry() added

- gtk/combo_box.go
* gtk_combo_box_new_with_model_and_entry
* gtk_combo_box_get_wrap_width
* gtk_combo_box_set_wrap_width
* gtk_combo_box_get_row_span_column
* gtk_combo_box_set_row_span_column
* gtk_combo_box_get_column_span_column
* gtk_combo_box_set_column_span_column
* gtk_combo_box_popup_for_device
* gtk_combo_box_get_has_entry
* gtk_combo_box_set_popup_fixed_width
* gtk_combo_box_get_popup_fixed_width
reordered some funcs to fit order in GTK documentation.
adding missing bindings at the bottom.
> adding multiple bindings for GtkComboBox

- gdk/gdk.go
- glib/glib.go
- gtk/accel.go
- gtk/gdk.go
- gtk/gtk.go
- gtk/gtk_deprecated_since_3_14.go
- gtk/gtk_deprecated_since_3_20.go
- gtk/gtk_since_3_12.go
- gtk/menu_since_3_22.go
- gtk/widget.go
- gtk/window.go
adds bindings for
* GdkWindowHints
* GdkGeometry
* gtk_window_set_geometry_hints()
* gtk_window_get_gravity()
* gtk_window_parse_geometry()
* gtk_window_get_resize_grip_area()
* gtk_widget_intersect()
* gtk_entry_get_text_area()
* gtk_entry_get_icon_area()
renames GdkGravity to Gravity to align with naming conventions.  
adjust GetPointingTo() to conform to golang coding conventions.
> adding several bindings

- gtk/font_chooser.go
* gtk_font_button_set_show_style()
* gtk_font_button_get_show_style()
* gtk_font_button_set_show_size()
* gtk_font_button_get_show_size()
* gtk_font_button_set_use_font()
* gtk_font_button_get_use_font()
* gtk_font_button_set_use_size()
* gtk_font_button_get_use_size()
* gtk_font_button_set_title()
* gtk_font_button_get_title()
> add bindings for GtkFontChooser

- CONTRIBUTIONS.md
- gdk/testing.go
- glib/glib.go
- glib/glib_test.go
- gtk/gtk.go
- gtk/gtk.go.h
- gtk/testing.go
- gtk/testing_deprecated_since_3_20.go
- gtk/testing_since_3_10.go
- gtk/testing_test.go
- gtk/window.go
- gtk/window_since_3_14.go
* gtk_test_find_label + unit test
* gtk_test_find_sibling + unit test
* gtk_test_find_widget + unit test
* gtk_test_init
* gtk_test_list_all_types + unit test
* gtk_test_register_all_types + unit test
* gtk_test_widget_send_key
* gdk_test_render_sync
* gdk_test_simulate_button
* gdk_test_simulate_key
* gtk_window_set_interactive_debugging
* gtk_window_list_toplevels
* g_type_is_a + unit test
* g_type_from_name + unit test
* g_type_next_base + unit test
Since 3.10:
* gtk_test_widget_wait_for_draw
Deprecated since 3.20:
* gtk_test_widget_click
> Testing-related functions

- README.md
- gdk/gdk_deprecated_since_3_10.go
- gdk/gdk_deprecated_since_3_16.go
- gdk/gdk_deprecated_since_3_20.go
- gdk/gdk_deprecated_since_3_22.go
- gtk/gtk_deprecated_since_3_10.go
- gtk/gtk_deprecated_since_3_12.go
- gtk/gtk_deprecated_since_3_14.go
- gtk/gtk_deprecated_since_3_16.go
- gtk/gtk_deprecated_since_3_18.go
- gtk/gtk_deprecated_since_3_20.go
- gtk/gtk_deprecated_since_3_22.go
- gtk/gtk_deprecated_since_3_24.go
- gtk/gtk_deprecated_since_3_8.go
- gtk/testing_deprecated_since_3_20.go
Optionally includes deprecated features in builds
See added documentation in the readme file how to use this. Please review & comment!  
This is a straightforward change, but could have bad consequences if I missed anything.
@MJacred you have a special case with issue gotk3/gotk3#516. Read this to see how to adjust your build tags accordingly.
Fixes gotk3/gotk3#253  
Closes gotk3/gotk3#475
Technical documentation, should be moved to the wiki if there are no objections to this change.
```go
// Package main is an example-user of gotk3
package main
import "github.com/gotk3/gotk3/gtk"
func main() {
gtk.dep_since_3_20()
gtk.since_3_16()
}
```
```go
// Filename: *_deprecated_since_3_20.go
// This file is compiled for all GTK versions below 3.20, and optionally with gtk_deprecated
// +build …
```
> Add gtk_deprecated build tag

- gtk/gtk.go
- gtk/gtk_export.go
- gtk/gtk_export_since_3_10.go
- gtk/gtk_export_since_3_14.go
- gtk/gtk_since_3_10.go
- gtk/gtk_since_3_12.go
- gtk/gtk_since_3_14.go
- gtk/gtk_since_3_20.go
- gtk/gtk_since_3_8.go
- gtk/print.go
- gtk/print_test.go
- gtk/widget_export_since_3_8.go
- gtk/widget_since_3_8.go
**Attention: Breaking Changes!**
* Use `[]interface{}` in callback signatures to have consistent "optional" user data (See #514)
* Use the READ-part of the RW locks where appropriate
* Clean up callbacks if possible (notably in ForEach calls)
* Also move the remaining cleanup TODOs next to each place where callbacks are registered
> Clean up cgo callbacks

- gtk/gtk_since_3_18.go
Removed required tag `gtk_3_18` from ` gtk/gtk_since_3_18.go` so this version is also built for higher versions ( 3.20, 3.22 ).
Workaround: Use the three tags when building `-tags gtk_3_18,gtk_3_20,gtk_3_22`
> Fix build tags for 3.18

- gtk/gtk.go
- gtk/gtk_since_3_10.go
* moved GtkBuilder to gtk since 3.10, which were misplaced
* added todos for missing GtkBuilder bindings since gtk 3.10
fixes #556
> added binding for gtk_builder_new_from_string()

- .travis.yml
- README.md
- glib/gvariant.go
- gtk/gtk_since_3_18.go
added testing for
* new Ubuntu 20.04
* go version 1.14
dropping testing for
* go version 1.8 (released 3 years ago)
* Ubuntu 14.04: only Extended Security Maintenance still running
> updated travis testing

- gtk/cell_area.go
`ToCellArea()` should return `*CellArea`, not `*C.GtkCellArea`
Current missing implementation makes it impossible to pass `gtk.CellAreaBox` to `gtk.TreeViewColumnNewWithArea()`
> CellArea did not fully implement ICellArea interface

- gtk/gtk.go
This PR adds the 4 missing functiions that acts on `*gdk.DragContext`.
> Added DragSetIcon{Widget,Surface,Name,Default}

- gtk/gtk.go
This PR fixes the two below crashes, as well as adding SelectionData into the list of known Glib marshalers for use in Connect callback arguments.
**Note:** This PR breaks existing code using `gtk.SetData(uintptr(unsafe.Pointer(v)), ...)`, which may or may not be a good thing (as the use of `uintptr` in the API should be discouraged).
The crash for SetData:
```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc8 pc=0x7f3fa47abba0]
runtime stack:
runtime.throw(0xd67467, 0x2a)
/nix/store/1r61f7iwqfb6dm1krqpj9cjfifjnfmjx-go-1.14.2/share/go/src/runtime/panic.go:1116 +0x72
runtime.sigpanic()
/nix/store/1r61f7iwqfb6dm1krqpj9cjfifjnfmjx-go-1.14.2/share/go/src/runtime/signal_unix.go:679 +0x46a
goroutine 1 [syscall, locked to thread]: …
```
> Added SelectionData into marshalers, fixed SetData and GetData crashing

- gtk/gtk.go
The Gtk reference documentation defines that [`gtk_text_tag_new`][1] can have a `NULL` name. This PR allows that by passing in an empty (`""`) string.
[1]: https://developer.gnome.org/gtk3/stable/GtkTextTag.html#gtk-text-tag-new
> Allow empty name in TextTagNew

- gtk/gtk.go
This PR is a follow up to https://github.com/gotk3/gotk3/pull/604, which does similar things but on `gtk.Entry`'s `SetIconFromPixbuf`, `SetIconFromIconName`, `SetIconTooltipText` and `SetIconTooltipMarkup` methods.
Reference documents: [GtkEntry#gtk-entry-set-icon-from-icon-name][1]
[1]: https://developer.gnome.org/gtk3/stable/GtkEntry.html#gtk-entry-set-icon-from-icon-name
> Make empty strings null in gtk.Entry's SetIcon methods

- gdk/gdk.go
- gtk/gtk.go
- gtk/gtk.go.h
- gtk/gtk_test.go
* GtkCellRendererCombo
* GtkCellRendererAccel
* GtkCellRendererSpin
* GtkCellRendererText.SetFixedHeightFromFont
* TODOs for missing GtkCellRenderer funcs
* Several Missing enums, enum members + marshaling functions
* Fix incorrect marshaling of gdk.ModifierType
(classified as flag type, not as enum)
> Extend wrappers for cell renderers

- gdk/gdk.go
I was running into some issues with the project (see #622). Thus I decided to implement this function, so that I could use Cairo surfaces in GtkCellRendererPixbuf objects.
> Implement gdk_pixbuf_get_from_surface

- gtk/gtk_since_3_12.go
Ran into an issue while reading the GtkDialog documentation and trying to create a dialog with a custom HeaderBar.
Found the additional flag [here](https://developer.gnome.org/gtk3/stable/GtkDialog.html#GtkDialogFlags)
> Add DIALOG_USE_HEADER_BAR to gtk.DialogFlags

- gdk/pixbuf.go
This PR adds the Go binding to [the `gdk_pixbuf_animation_get_static_image` function](https://developer.gnome.org/gdk-pixbuf/stable/gdk-pixbuf-Animations.html#gdk-pixbuf-animation-get-static-image).
> Add (*gdk.PixbufAnimation).GetStaticImage()

- gtk/gtk_since_3_10.go
```
$ go get github.com/gotk3/gotk3/gtk
/home/infinoid/go/src/github.com/gotk3/gotk3/gtk/gtk_since_3_10.go:124:15: undefined: errors
```
This error occurs on debian bullseye (testing), with these package versions:
```
ii  golang-1.14-go       1.14.7-2     amd64        Go programming language compiler, linker, compiled stdlib
ii  libcairo2-dev:amd64  1.16.0-4     amd64        Development files for the Cairo 2D graphics library
ii  libglib2.0-dev:amd64 2.64.4-1     amd64        Development files for the GLib library
ii  libgtk-3-dev:amd64   3.24.22-1    amd64        development files for the GTK library
```
Adding an import fixes it.
> Fix gtk_since_3_10.go

- gtk/text_mark.go
Rewrote GtkTextMark implementation and adding all methods
- Previous implementation of GtkTextMark was not really matching Gotk3 structure type (not descendant of GObject)
Gtk3 Specifications say in Object Hierarchy section:
GObject
╰── GtkTextMark
Now, it's ok.
- All methods linked with this object have been wrapped
- there is no change for previously written source code using GtkTextMark object.
- 'gtk.go' and 'gtk.go.h' has been modified to work right with these modifications (#657 and #658).
> Rewrote GtkTextMark implementation and adding all methods

- gio/gio.go
- gio/gio.go.h
- gio/utils.go
- gtk/gtk.go
- GIcon comes with marshaler, wrapper ... and:
g_icon_equal()
g_icon_to_string()
g_icon_new_for_string()
- GFileIcon comes with marshaler, wrapper ... and:
g_file_icon_new()
(the actual implementation is not really correct mixing GFileIcon and GFile to obtain a GIcon and was made under glib instead of gio ...)
take a look at: gotk3/glib/gfile.go and gotk3/glib/gicon.go
- GFile comes with marshaler, wrapper ... and:
g_file_new_for_path()
@andre-hub
My last PR: #656, #657, #658 and this one, are made to prepare GtkSource implementation that will come after merge.
Actually i've made implementation of GtkSourceView and his component (-+85%) and i use it into my own projects.
This will be usable for focal (sure) (20.04LTS) with libgtksourceview-4-dev and maybe (not sure) for xenial (16.04LTS), …
> Hfmrow patch g icon

- gtk/gtk.go
It is conditionally defined by [gtk_since_3_24.go](https://github.com/gotk3/gotk3/blob/master/gtk/gtk_since_3_24.go#L14), instead.
> Remove INPUT_PURPOSE_TERMINAL from gtk.go

- gtk/tree_view.go
This PR adds these following function bindings:
gtk_tree_view_enable_model_drag_dest
gtk_tree_view_enable_model_drag_source
gtk_tree_view_unset_rows_drag_source
gtk_tree_view_unset_rows_drag_dest
gtk_tree_view_set_drag_dest_row
gtk_tree_view_get_drag_dest_row
gtk_tree_view_get_dest_row_at_pos
> Added several missing GtkTreeView methods

- gtk/gtk.go
This commit adds bindings for these functions:
gtk_scale_add_mark()
gtk_scale_clear_marks()
> Add (*gtk.Scale).{Add,Clear}Marks bindings

- gtk/app_chooser.go
- gtk/cell_area.go
- gtk/combo_box.go
- gtk/gtk.go
- gtk/gtk.go.h
Add gtk_tree_model_get_string_from_iter.
Add GtkCellEditable & some GtkCellRenderer methods.
-Created Binding for GtkCellEditable
gtk_cell_editable_remove_widget
gtk_cell_editable_editing_done
gtk_cell_editable_start_editing
-GtkCellEditableIface + all object's implementation.
-I modified other objects to integrate them with the 'GtkCellEditable' interface: https://developer.gnome.org/gtk3/stable/GtkCellEditable.html#GtkCellEditable.implementations
So, GtkAppChooserButton, GtkComboBox, GtkComboBoxText, GtkEntry, GtkSearchEntry and GtkSpinButton have the 'GtkCellEditable' interface implemented correctly as the Gtk3 manual says.
-Add Binding for: GtkCellRenderer
gtk_cell_renderer_activate
gtk_cell_renderer_start_editing
gtk_cell_renderer_stop_editing
gtk_cell_renderer_get_visible …
> Add some bindings TreeModel, CellRenderer, CellEditable

- gtk/label.go
- pango/pango-attributes.go
I've implemented a few functions to allow the usage of Pango attributes to disable automatic hyphenation on labels.
> Make it possible to disable hyphenation on labels

- gtk/gtk.go
was previously crashing with error "cgo argument has Go pointer to Go pointer"
fixes #614 
current implementation still crashes on inserting gdk.Pixbuf, but at least the error is different:
```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x80 ...]
```
A custom func like in `SetValue` is required, I guess...
> [WIP] allow passing gdk.Pixbuf to TreeStore.InsertWithValues()

- glib/connect.go
- glib/glib.go
Prior to this code, concurrent calls to `object.Connect` might cause a `panic: concurrent map writes` crash. As GLib is meant to be thread-safe (and the `closures` map is already guarded inside a mutex), the `signals` map (the origin of the crash) should also be guarded.
> Fixed glib signals missing mutex

- gdk/pixbuf_since_2_4.go
- gdk/pixbuf_since_2_4.go.h
This PR adds partial `gdk_pixbuf_save_callback` support by supporting the idiomatic `io.Writer` API instead.
> Add Pixbuf Save stream to io.Writer API

- gdk/pixbuf.go
This pull request adds the `Fill` and `AddAlpha` bindings for `*gdk.Pixbuf`.
> Add Pixbuf Fill and AddAlpha bindings

- cairo/region.go
Add cairo Region, Overlap, Rectangle bindings
Add  cairo_region_t, cairo_region_overlap_t, cairo_rectangle_int_t
cairo_rectangle_int_t -> func, methods to handle it
Fully implemented cairo_region_t:
cairo_region_create
cairo_region_create_rectangle
cairo_region_create_rectangles
cairo_region_copy
cairo_region_reference
cairo_region_destroy
cairo_region_status
cairo_region_get_extents
cairo_region_num_rectangles
cairo_region_get_rectangle
cairo_region_is_empty
cairo_region_contains_point
cairo_region_overlap_t
cairo_region_contains_rectangle
cairo_region_equal
cairo_region_translate
cairo_region_intersect
cairo_region_intersect_rectangle
cairo_region_subtract
cairo_region_subtract_rectangle
cairo_region_union
cairo_region_union_rectangle
cairo_region_xor
cairo_region_xor_rectangle
> Add cairo Region, Overlap, Rectangle bindings

- .travis.yml
remove old go version builds from travis CI
> clean up travis ci file

- gtk/gtk.go
Altered file: gtk.go
gtk_range_get_fill_level()
gtk_range_get_restrict_to_fill_level()
gtk_range_get_show_fill_level()
gtk_range_set_fill_level()
gtk_range_set_restrict_to_fill_level()
gtk_range_set_show_fill_level()
gtk_range_get_adjustment()
gtk_range_set_adjustment()
gtk_range_get_round_digits()
gtk_range_set_round_digits()
gtk_range_set_lower_stepper_sensitivity()
gtk_range_get_lower_stepper_sensitivity()
gtk_range_set_upper_stepper_sensitivity()
gtk_range_get_upper_stepper_sensitivity()
gtk_range_get_flippable()
gtk_range_set_flippable()
gtk_range_get_range_rect()
gtk_range_get_slider_range()
gtk_range_get_slider_size_fixed()
gtk_range_set_slider_size_fixed()
> Add some GtkRange bindings

- glib/glib.go
It could be useful for some to have bindings to those functions.
https://developer.gnome.org/glib/stable/glib-Miscellaneous-Utility-Functions.html#g-get-prgname
> Add Prgname getter and setter

- glib/glib.go
See issue #727 for details.  This patch fixes the problem by
unconditionally copying the contents of the return value.
> It is not safe to reference memory returned in a signal callback.

- gtk/accel.go
This PR fixes the problem with the GtkAccelKey declaration described below.
Its purpose is to help users, like me, who want to test future v1.16 functionality, while using the gotk3 library, and to facilitate discussion about this to make this solution the best it can be for everyone.
altered file: 'accel.go'
Golang 1.16 - Cgo changes [Go 1.16 Release Notes - The Go Programming Language](https://tip.golang.org/doc/go1.16#cgo):
The cgo tool will no longer try to translate C struct bitfields into Go struct fields, even if their size can be represented in Go. The order in which C bitfields appear in memory is implementation dependent, so in some cases the cgo tool produced results that were silently incorrect.
'C' struct definition:
```c
struct GtkAccelKey {
guint           accel_key; …
```
> Solve GtkAccelKey issue with golang 1.16

- gtk/menu.go
- gtk/menu_since_3_22.go
add:
gtk_menu_get_reserve_toggle_size()
gtk_menu_set_reserve_toggle_size()
gtk_menu_place_on_monitor()
gtk_menu_popup_at_rect()
gtk_menu_get_attach_widget()
gtk_menu_set_active()
gtk_menu_get_active()
gtk_menu_get_monitor()
gtk_menu_set_monitor()
gtk_menu_attach()
gtk_menu_set_screen()
gtk_menu_new_from_model()
> add bindings to GtkMenu

- gdk/pixbuf.go
* `gdk.PixbufNewFromResource()` => [gdk_pixbuf_new_from_resource()](https://developer.gnome.org/gdk-pixbuf/stable/gdk-pixbuf-File-Loading.html#gdk-pixbuf-new-from-resource)
* `gdk.PixbufNewFromResourceAtScale()` =>  [gdk_pixbuf_new_from_resource_at_scale()](https://developer.gnome.org/gdk-pixbuf/stable/gdk-pixbuf-File-Loading.html#gdk-pixbuf-new-from-resource-at-scale)
> Adds bindings for gdk_pixbuf_new_from_resource() and gdk_pixbuf_new_from_resource_at_scale()

- gtk/gtk.go
* `(v *CellLayout) ClearAttributes()` => [`gtk_cell_layout_clear_attributes()`](https://developer.gnome.org/gtk3/stable/GtkCellLayout.html#gtk-cell-layout-clear-attributes)
> Adds binding for gtk_cell_layout_clear_attributes()

- glib/gaction.go
- glib/glib.go
- glib/gvariant.go
Register GValue marshalers for:
- GSimpleAction
- GAction
- GPropertyAction
- Add marshaller for GVariant (WIP)
Add:
- g_action_print_detailed_name()
- g_variant_parse()
> Solving #741- Add possibility to use GVariant in signal handler 

- pango/pango-attributes.go
- pango/pango-attributes_since_1_44.go
This pull request adds the build tag `pango_1_42` that would omit `AttrInsertHyphensNew` to allow building on older Ubuntu systems with `go build -tags pango_1_42`.
> Add build tag pango_1_42 for Pango

- gtk/gtk_since_3_10.go
To remove a header from a ListBoxRow, SetHeader is called with header == nil.
However this results in a runtime error (nil pointer dereference).
I fixed it with this commit. However, from definition of toWidget() I see that header.toWidget() should actually return nil. Why does that not work? Is there any better way to fix it?
> fix crash in SetHeader if header is nil

- gtk/gtk.go
---
"unrecognized class name GtkButtonBox"
Appears when the '**castInternal**' function is used.
- Added a button in GtkDialogMessage.
- button.GetParent ()
- "unrecognized class name GtkButtonBox"
> Adding missing 'GtkButtonBox' to gotk3 'WrapMap'

- glib/glib.go
The fix made in e5dd2587cdc1 and outlined in bug #727 seems to have been
accidentally re-introduced in commit cf79ce840c3f (presumably because of
a merge conflict).  The same reproducer in the bug report can be used to
trigger this issue and validate the fix in this commit.
> Fix dangerous memory reference again.

- glib/connect.go
- glib/glib.go
- glib/glib.go.h
- glib/gmain_context.go
- internal/closure/funcstack.go
More performant {Idle,Timeout}Add
This commit changes the IdleAdd and TimeoutAdd functions to use the
g_full functions instead of the GClosure and g_source_attach API.
The reason for this change was because both of these removed APIs hog a
lot of CPU time for weird reasons and will eventually lag behind after a
long time of usage. The new functions don't have this issue at all.
A type check cache is also implemented just for IdleAdd and TimeoutAdd
functions, because these functions are potentially uesd for critical
functionality and should therefore be fast if possible.
glib.MainContext's Acquire method is also changed to return a boolean in
accordance to what's put in the GLib Main Loop documentation.
> More performant {Idle,Timeout}Add

- glib/glib.go
This pull request is a follow-up to #773 that fixes the default Priority of the added callbacks.
> Fix incorrect Idle priority

- gdk/pixbuf.go
Fixed the error checking in `PixbufNewFromDataOnly`
This function is also identical to `PixbufNewFromBytesOnly`, maybe in a future major version remove one of the functions.
> Fixed error checking in PixbufNewFromDataOnly

- glib/quark.go
- gtk/glarea.go
This PR:
* Adds a wrapper for `g_quark_from_string`
* Adds a wrapper for `gtk_gl_area_set_error`
> Implement GLArea.SetError

- glib/quark.go
Windows build fails with this error:
> D:\workspace\go\gopath\pkg\mod\github.com\gotk3\gotk3@v0.6.0\glib\quark.go:13:8: could not determine kind of name for C.free
The issue have already been reported #444 a while ago on another file and the solution was to add the C import `<stdlib.h>`.
After adding this manually to the file the build succeed
> Add missing C #include in glib/quark.go

- gtk/style.go
This pull request adds the binding for [gtk_render_background](https://developer.gnome.org/gtk3/stable/GtkStyleContext.html#gtk-render-background).
> Add gtk.RenderBackground

- cairo/fontoptions.go
This pull request adds bindings for [`cairo_font_options_t`](https://cairographics.org/manual/cairo-cairo-font-options-t.html#cairo-font-options-set-subpixel-order).
> Add cairo.FontOptions

- glib/glib_since_2_58.go
Missed these imports on 2.58 and higher in the previous PR. Sorry about that.
> Fix compile on GLib 2.58 and higher

- cairo/canvas.go
- cairo/fontoptions.go
- cairo/pattern.go
- cairo/region.go
- cairo/surface.go
- gdk/gdk.go
- gdk/gdk_deprecated_since_3_20.go
- gdk/gdk_since_3_10.go
- gdk/pixbuf.go
- gdk/pixbuf_since_2_12.go
- gdk/pixbuf_since_2_32.go
- gdk/pixbuf_since_2_4.go
- gdk/pixbuf_since_2_6.go
- glib/finalizers.go
- glib/gicon.go
- glib/glib.go
- glib/gvariant.go
- glib/gvarianttype.go
- gtk/application.go
- gtk/gtk.go
- gtk/gtk_since_3_12.go
- gtk/icon_view.go
- gtk/print.go
- gtk/print_since_3_16.go
- gtk/text_view.go
- gtk/tree_view.go
- gtk/widget.go
- gtk/window.go
- gtk/windowgroup.go
- pango/pango-layout.go
This PR adds the necessary machinery for making it possible for clients to avoid the problem in #810. The idea is to add a global `FinalizerStrategy` variable which by default will only call the function directly. But a client having problems with the UI thread can use this variable to hook in to the strategy and do something else during the finalization process.
> Fix finalizer bad thread interaction

- glib/gbinding.go
As explained here #830, #826 should not have been merged.
Edit: I've tried to reverse #826 but without success, i think it's because the [Merge branch 'master' into Update-glib-binding>2.66](https://github.com/gotk3/gotk3/commit/46994fb89f0c40d273e49c7c48e204aef3769784) is disabling this ability.
So, this pr simply removes this part of the code (below) added with the merge of #826, because it is already present (in corrected version) in the file [gbinding_since_2_68.go](https://github.com/gotk3/gotk3/blob/master/glib/gbinding_since_2_68.go)
```go
// Retrieves the GObject instance used as the source of the binding
func (v *Binding) GetSource() *Object {
// 	obj := C.g_binding_get_source(v.native())
obj := C.g_binding_dup_source(v.native())
if obj == nil {
return nil
}
return …
```
> #826 merging correction.

- glib/glib_test.go
- gtk/print_test.go
We adjust the signatures of the `IdleAdd()`, `TimeoutAdd()` and `ForEach()` function calls used in tests to match the actual implementation, fixing `go test` runs.
Closes #844.
> adjust function signatures in tests

- glib/glib.go
- glib/glib.go.h
This PR closes #851 and #842, adding the new binding for g_signal_newv() allows one to create signals with defined number of extra parameters and their types.
> Adding new function SignalNewV, wrapper around g_signal_newv()

- gtk/font_chooser.go
- gtk/gtk.go.h
Example usage:
```
d, _ := gtk.FontChooserDialogNew("Choose Font", win)
d.Run()
fmt.Println("choosen font:", d.GetFont())
d.Destroy()
```
> Added FontChooserDialog to gotk3

- gtk/color_chooser.go
Think this is a typo, unless I'm reading the code wrong.
> Fixed typo for GtkColorChooserDialog native comment.

- glib/gbinding_since_2_68.go
The current HEAD doesn't build on older Glib versions. This commit simply adds the tags where not to build it, following previous formats.
The only difference is that it also supplies the build tags in both the old and new format, something which is recommended for libraries that will be used from many different Golang versions.
> Update Binding build tags to only build on later versions of Glib. 

- gtk/widget.go
Implemented:
- gtk_widget_unset_state_flags as Widget.UnsetStateFlags(StateFlags)
- gtk_widget_get_state_flags as GetStateFlags() StateFlags
Tested on go1.21.6
> Implement gtk_widget_unset_state_flags and gtk_widget_get_state_flags

- gtk/gtk.go
See https://docs.gtk.org/gtk3/method.Paned.get_handle_window.html
> Fix Paned.GetHandleWindow(): should return gdk.Window, not gtk.Window

- gtk/gtk.go
> Revert "Fix Paned.GetHandleWindow(): should return gdk.Window, not gtk.Window"

- gtk/gtk_test.go
This PR adds the missing type parameter to an `Emit()` call in `gtk_test.go` causing tests to fail.
Closes #917
> Add missing parameter in test Emit call

- gdk/gdk.go
This absolutely feels like the wrong place to me, however according to the GTK docs, it should be on the event (https://docs.gtk.org/gdk3/method.Event.get_scancode.html) rather than the EventKey. In my testing this is always 0, however I think this is a characteristic of my environment (Debian 12 + X11) rather than this being broken
Fixes: https://github.com/gotk3/gotk3/issues/919
> Implementing gdk_event_get_scancode

- gtk/gtk.go
- gtk/gtk_test.go
Noticed the handler for the [CssProvider::parsing-error](https://docs.gtk.org/gtk3/signal.CssProvider.parsing-error.html) signal was being given a `*glib.Object` as its first argument, instead of a `*gtk.CssProvider`.
The comment changes must have been `gofmt`...
> Add marshaler for CssProvider
